name: Rust

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Get current version
        id: current
        run: |
          ver=$(grep '^version' Cargo.toml | head -1 | sed 's/version = "\(.*\)"/\1/')
          echo "version=$ver" >> $GITHUB_OUTPUT

      - name: Get previous version from main
        id: previous
        run: |
          git fetch origin main --depth=1
          prev_ver=$(git show origin/main:Cargo.toml | grep '^version' | head -1 | sed 's/version = "\(.*\)"/\1/')
          echo "version=$prev_ver" >> $GITHUB_OUTPUT

      - name: Check for version change
        id: changed
        run: |
          if [ "${{ steps.current.outputs.version }}" != "${{ steps.previous.outputs.version }}" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
          else
          echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Publish
        if: steps.changed.outputs.changed == 'true'
        run: cargo publish
