name: Rust

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: ${{ matrix.os }}
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Get current version
        id: current
        run: |
          ver=$(grep '^version' Cargo.toml | head -1 | sed 's/version = "\(.*\)"/\1/')
          echo "version=$ver" >> $GITHUB_OUTPUT

      - name: Get previous version from main
        id: previous
        run: |
          prev_ver=$(git show HEAD^:Cargo.toml | grep '^version' | head -1 | sed 's/version = "\(.*\)"/\1/')
          echo "version=$prev_ver" >> $GITHUB_OUTPUT

      - name: Check for version change
        id: changed
        run: |
          if [ "${{ steps.current.outputs.version }}" != "${{ steps.previous.outputs.version }}" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
          else
          echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Publish to crates.io
        if: steps.changed.outputs.changed == 'true'
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo publish --allow-dirty

      - name: Tag and push version
        if: steps.changed.outputs.changed == 'true'
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "v${{ steps.current.outputs.version }}"
          git push origin "v${{ steps.current.outputs.version }}"

      # - name: Build binary
      #   run: cargo build --release
      #
      # - name: Rename binary (Linux/macOS)
      #   if: ${{ runner.os != "Windows" }}
      #   run: mv target/release/voxlan target/release/voxlan-${{ runner.os }}
      #
      # - name: Rename binary (Windows)
      #   if: ${{ runner.os == 'Windows' }}
      #   run: ren target\release\voxlan.exe voxlan-windows.exe
      #   shell: cmd
      #
      # - name: Create Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: v${{ steps.current.outputs.version }}
      #     repo-token: "${{ secrets.GITHUB_TOKEN }}"
      #
      # - name: Upload Release Asset (Linux/macOS)
      #   uses: softprops/action-gh-release@v2
      #   if: runner.os != 'Windows'
      #   with:
      #     files: target/release/voxlan-${{ runner.os }}
      #     tag_name: v${{ steps.current.outputs.version }}
      #   env:
      #     repo-token: "${{ secrets.GITHUB_TOKEN }}"
      #
      # - name: Upload Release Asset (Windows)
      #   uses: softprops/action-gh-release@v2
      #   if: runner.os ==  'Windows'
      #   with:
      #     repo-token: "${{ secrets.GITHUB_TOKEN }}"
      #     files: target/release/voxlan-windows.exe
      #     tag_name: v${{ steps.current.outputs.version }}
